export enum GraphStyle {
    TREE = 'TREE',
    TREE_VERTICAL = 'TREE_VERTICAL',
    RADIAL_TREE = 'RADIAL_TREE',
    DAG = 'DAG',
    FORCE_DIRECTED = 'FORCE_DIRECTED',
    CIRCULAR_GRAPH = 'CIRCULAR_GRAPH',
    TREE_MAP = 'TREE_MAP',

}